export const categories = [
  // Electronics
  "Electronics",
  "Smartphones",
  "Mobile Accessories",
  "Tablets",
  "Laptops",
  "Desktop Computers",
  "Computer Accessories",
  "Monitors",
  "Printers & Scanners",
  "Computer Components",
  "Networking Devices",
  "Cameras",
  "Camera Accessories",
  "Headphones & Earphones",
  "Speakers",
  "Smartwatches",
  "Wearable Technology",
  "Televisions",
  "Home Audio",
  "Gaming Consoles",
  "Gaming Accessories",
  "Electronic Accessories",
  "Power Banks",
  "Chargers & Adapters",
  "Cables & Connectors",

  // Fashion
  "Fashion",
  "Men's Clothing",
  "Women's Clothing",
  "Kids' Clothing",
  "Baby Clothing",
  "Traditional Clothing",
  "T-Shirts",
  "Shirts",
  "Jeans",
  "Trousers",
  "Shorts",
  "Jackets & Coats",
  "Dresses",
  "Sarees",
  "Kurtas & Kurtis",
  "Ethnic Wear",
  "Innerwear",
  "Sleepwear",
  "Sportswear",
  "Shoes",
  "Sandals",
  "Slippers",
  "Sneakers",
  "Bags & Backpacks",
  "Handbags",
  "Wallets",
  "Belts",
  "Sunglasses",
  "Fashion Accessories",

  // Beauty & Personal Care
  "Beauty & Personal Care",
  "Skincare",
  "Hair Care",
  "Makeup",
  "Fragrances",
  "Men's Grooming",
  "Women's Grooming",
  "Bath & Body",
  "Oral Care",
  "Personal Hygiene",
  "Beauty Tools",
  "Hair Styling Tools",

  // Home & Kitchen
  "Home & Kitchen",
  "Kitchen Appliances",
  "Cookware",
  "Bakeware",
  "Kitchen Utensils",
  "Dinnerware",
  "Glassware",
  "Storage & Organization",
  "Home Decor",
  "Home Furnishing",
  "Bedding",
  "Bedsheets",
  "Curtains",
  "Cushions & Pillows",
  "Carpets & Rugs",
  "Lighting",
  "Clocks",
  "Wall Decor",
  "Furniture",
  "Sofas",
  "Beds",
  "Tables",
  "Chairs",
  "Wardrobes",
  "Office Furniture",
  "Cleaning Supplies",

  // Grocery & Food
  "Groceries",
  "Fruits & Vegetables",
  "Dairy & Eggs",
  "Bakery",
  "Snacks",
  "Beverages",
  "Tea & Coffee",
  "Packaged Foods",
  "Cooking Essentials",
  "Spices & Masala",
  "Rice & Grains",
  "Pulses & Lentils",
  "Oils & Ghee",
  "Sweets & Chocolates",

  // Health
  "Health & Wellness",
  "Vitamins & Supplements",
  "Fitness & Nutrition",
  "Medical Supplies",
  "First Aid",
  "Healthcare Devices",
  "Personal Care",

  // Sports
  "Sports & Fitness",
  "Gym Equipment",
  "Exercise & Yoga",
  "Running",
  "Cycling",
  "Outdoor Sports",
  "Cricket",
  "Football",
  "Badminton",
  "Tennis",
  "Swimming",
  "Sports Accessories",
  "Sports Shoes",
  "Fitness Accessories",

  // Books & Education
  "Books",
  "Academic Books",
  "School Books",
  "College Books",
  "Competitive Exam Books",
  "Engineering Books",
  "Computer & Programming Books",
  "Fiction",
  "Non-Fiction",
  "Comics & Graphic Novels",
  "Children's Books",
  "Educational Materials",
  "Educational Toys",

  // Toys & Baby
  "Toys & Games",
  "Baby Products",
  "Baby Care",
  "Baby Feeding",
  "Baby Gear",
  "Diapers",
  "Toys",
  "Board Games",
  "Puzzles",
  "Action Figures",
  "Dolls",
  "Remote Control Toys",
  "Outdoor Toys",

  // Jewellery & Watches
  "Jewellery",
  "Gold Jewellery",
  "Silver Jewellery",
  "Fashion Jewellery",
  "Necklaces",
  "Earrings",
  "Rings",
  "Bracelets",
  "Bangles",
  "Watches",
  "Men's Watches",
  "Women's Watches",
  "Kids' Watches",
  "Watch Accessories",

  // Automotive
  "Automotive",
  "Car Accessories",
  "Bike Accessories",
  "Car Care",
  "Bike Care",
  "Car Electronics",
  "Helmets",
  "Vehicle Lighting",
  "Tyres & Accessories",
  "Tools & Equipment",

  // Pet Supplies
  "Pet Supplies",
  "Dog Supplies",
  "Cat Supplies",
  "Pet Food",
  "Pet Toys",
  "Pet Grooming",
  "Pet Accessories",

  // Stationery & Office
  "Stationery",
  "School Supplies",
  "Office Supplies",
  "Pens & Pencils",
  "Notebooks",
  "Diaries",
  "Art Supplies",
  "Craft Supplies",
  "Office Equipment",

  // Musical Instruments
  "Musical Instruments",
  "Guitars",
  "Keyboards & Pianos",
  "Drums & Percussion",
  "Wind Instruments",
  "String Instruments",
  "Microphones",
  "Audio Accessories",

  // Tools & Hardware
  "Tools & Hardware",
  "Hand Tools",
  "Power Tools",
  "Hardware Accessories",
  "Electrical Supplies",
  "Safety Equipment",

  // Travel
  "Travel & Luggage",
  "Suitcases",
  "Travel Bags",
  "Backpacks",
  "Travel Accessories",

  // Other
  "Gift Items",
  "Party Supplies",
  "Religious & Spiritual Products",
  "Garden & Outdoor",
  "Industrial Supplies",
  "Digital Products",
  "Other",
]